MANAGER_NAME=$1
DB_USERNAME=anurat
DB_PASSWORD=abcd
DOCKER_IMAGE_BROKER=test
DOCKER_IMAGE_MANAGER=manager
POSTGRES_CONTAINER=p2


docker run --name $MANAGER_NAME -d -p 0:5142 --expose 5142 -e DB_USERNAME=$DB_USERNAME -e DB_PASSWORD=$DB_PASSWORD -e DOCKER_IMAGE_BROKER=$DOCKER_IMAGE_BROKER -e POSTGRES_CONTAINER=$POSTGRES_CONTAINER --rm $DOCKER_IMAGE_MANAGER
